# Generated by Django 3.2.9 on 2021-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addhar', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quali', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('add1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
            ],
        ),
    ]
