# Generated by Django 3.2.9 on 2021-11-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20211121_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deta',
            new_name='new',
        ),
    ]
