# Generated by Django 3.2.9 on 2021-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_rename_deta_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aut',
            name='id',
        ),
        migrations.AlterField(
            model_name='aut',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
