# Generated by Django 3.2.7 on 2021-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('pho', models.IntegerField(max_length=20)),
                ('un', models.CharField(max_length=50)),
                ('ps', models.CharField(max_length=50)),
            ],
        ),
    ]
