# Generated by Django 3.2.7 on 2021-09-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_deta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deta',
            name='add1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deta',
            name='add2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='deta',
            name='qua',
            field=models.CharField(max_length=500),
        ),
    ]
