# Generated by Django 3.2.7 on 2021-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20210929_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='deta',
            name='adh',
            field=models.CharField(default='', max_length=500),
        ),
    ]
